# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'a3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for a3
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift', '~> 7.0-beta'

end
